### ISSUE TITLE
Is this typo??

### ISSUE THREAD

**Issue by kishorevaishnav** [eddyerburgh/vue-test-utils-vuex-example#2]
NOT A BUG.

But is this typo ??  https://github.com/eddyerburgh/vue-test-utils-vuex-example/blob/master/src/store/index.js#L41 as `Vue.use(Vuex)` is already used in the top.

**Comment by eddyerburgh** [comment]
Thanks for this. Yes this is a typo. Can you make a PR to remove it?

**Comment by kishorevaishnav** [comment]
Thanks & here is the PR https://github.com/eddyerburgh/vue-test-utils-vuex-example/pull/3

**Comment by eddyerburgh** [comment]
Thanks 🙂
