### ISSUE TITLE
Testing components that use Vuex modules

### ISSUE THREAD

**Issue by thehavoc** [eddyerburgh/vue-test-utils-vuex-example#4]
I'm training to test my components that use Vuex modules by following the [Module](https://github.com/eddyerburgh/vue-test-utils-vuex-example/blob/master/test/unit/specs/Modules.spec.js) example.

However, when I run the tests, there are warnings like this one:
```
[vuex] module namespace not found in mapGetters(): 
```

An example test can be seen on [NewQuickTask.spec.js](https://github.com/thehavoc/dailytasks/blob/master/tests/JavaScript/components/NewQuickTask.spec.js)

This is the code of the first getter that throws the above error: [errors.js](https://github.com/thehavoc/dailytasks/blob/master/resources/assets/js/mixins/errors.js).

This is the module: [store/modules/errors.js](https://github.com/thehavoc/dailytasks/blob/master/resources/assets/js/store/modules/errors.js).

I'd like to check if you know what might cause these warnings. Thanks.

**Comment by thehavoc** [comment]
I've just figured it out. The modules have to be explicitly loaded as modules by Vuex in the spec file. For example: 
```
	beforeEach (() => {
		store = new Vuex.Store({
			state: {},
			modules: {
				errors,
				tasks
			}
		});
	});
```

I hope this will be helpful for others that experience the same problem.

**Comment by francescq** [comment]
What happens when the app has lots of nested modules?
The component is coupled with the store module. If we have to create all the structure to satisfy the namespaced modules makes the test unmaintainable.

Is there any way to just use the vuex module needed so it's not needed to create the whole store?
Am I missing something obvious?

**Comment by VRuzhentsov** [comment]
@francescq i'm using something like
``` js
import * as permissionsModule from "~/store/permissions";
import cloneDeep from "lodash/cloneDeep";


const store = new Vuex.Store({
    state: { },
    modules: {
      permissions: cloneDeep(permissionsModule)
    }
  });
```
