### ISSUE TITLE
thank you so much for the example. question? where does the jest.fn() come from?

### ISSUE THREAD

**Issue by kengres** [eddyerburgh/vue-test-utils-vuex-example#5]

**Comment by eddyerburgh** [comment]
Jest adds a jest object to the node global object when it runs —https://facebook.github.io/jest/docs/en/jest-object.html#content

**Comment by kengres** [comment]
@eddyerburgh I was using mocha webpack to test my components. I decided to use  jest instead later on. I'm a beginner in testing. so that's why it didn't understand. thank you for the help
