### ISSUE TITLE
where is jest.fn() called from since it was'nt imported?

### ISSUE THREAD

**Issue by kengres** [eddyerburgh/vue-test-utils-vuex-example#6]
https://github.com/eddyerburgh/vue-test-utils-vuex-example/blob/a9381485c72e89beb9a85d8350e168ecc420cd61/test/unit/specs/Actions.spec.js#L15

**Comment by eddyerburgh** [comment]
Jest adds `jest` as a global object—https://facebook.github.io/jest/docs/en/jest-object.html
